predict-idlab/plotly-resampler

.gitignore, plotly_resampler/__init__.py, poetry.lock, pyproject.toml
Updates the .gitignore and update depencies to https://github.com/predict-idlab/trace-updater/pull/1.
=> :rocket: Update dependencies

plotly_resampler/figure_resampler.py
Fixes a bug int he `FigureResampler.add_trace` method when `hf_y` is a list.
=> :bug: fix bug in add_trace when hf_y is a list

plotly_resampler/figure_resampler.py, tests/test_figure_resampler.py
Eventually settled for asserting that high-frequency traces (i.e., `x` and `y` or `hf_x` and `hf_y`) are 1 dimensional.
This is slightly different behavior from plotly (where this is supported, but gives rather unexpected plots). Supporting this would (1) require us to change our internal structure (as we store `hf_series` internally: explicitly 1D data) while (2) most-likely enabling weird / unexpected plots.
Example of a weird / unexpected plot
```py
import pandas as pd
import numpy as np
import plotly.graph_objects as go
df = pd.DataFrame(index=np.arange(100), data={"a": np.arange(100)})
fig = go.Figure()
fig.add_trace(
go.Scatter(
x=df.index,
y=df[["a"]],  # (100, 1) shape
)
)
fig.show()
```
If we wrap `fig` with plotly-resampler its `FigureResampler` an AssertionError will be thrown …
=> :bug: assert dimensionality of high-frequency traces

examples/README.md, examples/dash_apps/construct_dynamic_figures.py, plotly_resampler/downsamplers/downsampling_interface.py, plotly_resampler/figure_resampler.py, plotly_resampler/utils.py, poetry.lock, pyproject.toml, tests/test_downsamplers.py, tests/test_figure_resampler.py, tests/test_figure_resampler_selenium.py, tests/test_utils.py
New features:
- Updated traceupdater to v0.0.8 where partial graph-ID matching is performed (is needed for the basic example)
- Decoupled the `register_update_graph` function so that it is more convenient to create dynamic callbacks.
---
TODO:
=> 🔥 show Aggregation bin-size in legend text + dynamic callback support

plotly_resampler/figure_resampler.py
This PR solves issue #36 
Note: I benchmarked `.is_integer` vs the current `isinstance` checking. My findings are that `.is_integer` is slightly slower, but this is a constant (minor) difference, meaning that just like for type checking the runtime does not deteriorate for longer index lengths.
=> :recycle: comply with new pandas index handling

README.md, docs/sphinx/getting_started.rst, plotly_resampler/figure_resampler/figurewidget_resampler.py, tests/test_figurewidget_resampler.py
This pr introduces the `FigureWidgetResampler.reset_axes` method, which allows performing a `reset_axes` after adjusting the `hf_data` properties of the `FigureWidgetResampler` instance.
Should resolve #45
TODO:
=> 🦌 Adding reset-axes functionality

plotly_resampler/figure_resampler/figure_resampler.py, plotly_resampler/figure_resampler/figure_resampler_interface.py, plotly_resampler/figure_resampler/figurewidget_resampler.py, plotly_resampler/figure_resampler/utils.py, tests/conftest.py, tests/test_aggregators.py, tests/test_composability.py, tests/test_figure_resampler.py, tests/test_figurewidget_resampler.py, tests/test_utils.py
To cope with better integration of other libraries we think that composing figures should be possible. 
relevant #70, #68
i.e. having a `FigureWidget` as input to a`FigureResampler or wrapping a `FigureResampler` with a `FigureWidgetResampler`
This PR. contains the code-base to tackle this issue. 
**main compose takeaway**:  Each composer will output the visualization at its full scale (i.e., if a zoomed in figurewidget(resampler) is composed, that composed object will show the (aggregated) unzoomed data)
notebook to replicate functionality and aid with tests: [register_pr.zip](https://github.com/predict-idlab/plotly-resampler/files/8884757/register_pr.zip)
TODO:
I would rewrite the docs on the `register_pr` branch, as this is tightly coupled with that one
=> 🗳️ Compose figs

plotly_resampler/figure_resampler/figure_resampler.py, plotly_resampler/figure_resampler/figure_resampler_interface.py, plotly_resampler/figure_resampler/figurewidget_resampler.py, tests/test_composability.py
Allows to use all the arguments of the `add_traces` function; e.g. `limit_to_views`, `max_n_samples`, ...
=> ✨ adding `convert_traces_kwargs`

plotly_resampler/aggregation/aggregation_interface.py, plotly_resampler/figure_resampler/figure_resampler_interface.py, tests/test_figure_resampler.py, tests/test_figurewidget_resampler.py
=> Fix numeric `hf_y` input as dtype object

plotly_resampler/figure_resampler/figure_resampler.py, plotly_resampler/figure_resampler/figure_resampler_interface.py, plotly_resampler/figure_resampler/figurewidget_resampler.py, tests/test_figure_resampler.py, tests/test_figurewidget_resampler.py
This PR does;
=> this is in line with the vanilla plotly behavior (see `BaseFigure` constructor documentation)
=> :fire: add support for figure dict input + propagate _grid_str

plotly_resampler/figure_resampler/figure_resampler.py, plotly_resampler/figure_resampler/figure_resampler_interface.py, tests/test_registering.py, tests/test_serialization.py
This PR does;
(*this is because [the default plotly figure height is 450](https://plotly.com/python/reference/layout/#layout-height), but [the default jupyter-dash app height is 650](https://github.com/plotly/jupyter-dash/blob/86e5746615b78c84ba4c31f6ccf8ea0da3174373/jupyter_dash/jupyter_app.py#L460-L464)* :point_right: :point_left: )
This PR adds the following behavior to `FigureResampler`; when having `fig` as output in your notebook (`_ipython_display_`) -> now a dash app will be started under the hood with `mode = "inline"`
Users can control the port and other properties of the dash app via the `show_dash_kwargs` that is added to the constructor of `FigureResampler`. This can be set in two manners;
- `fig = FigureResampler(..., show_dash_kwargs=dict(port=8051))`
- …
=> :sunrise: FigureResampler display improvements

plotly_resampler/figure_resampler/figure_resampler.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/fr_selenium.py, tests/test_figure_resampler.py, tests/test_figure_resampler_selenium.py
This PR does;
Look more into;
This PR adds additional JavaScript code to the `IPython.display.display` method, which contains a base64 bytarray image of the shown figure. When the dash app is not reachable, the image is shown instead of the iframe (which embedded the connected dash app). This works because the JavaScript in the notebook output cells gets executed each time a notebook is loaded (:exclamation: the kernel should not be running for this to happen).
We create a `JupyterDash` subclass which extends the "inline" visualization capabilities with the functionality described above.
This extension is triggered when *"inline_persistent" *is used in the `FigureResampler.show_dash` method
* we add a unique `_uid` to each object
* we add a new endpoint to the underlying flask app that
1. …
=> :robot: hack together output retention in notebooks

.github/workflows/test.yml, CONTRIBUTING.md, plotly_resampler/figure_resampler/figure_resampler.py, plotly_resampler/figure_resampler/figure_resampler_interface.py, plotly_resampler/figure_resampler/figurewidget_resampler.py, tests/conftest.py, tests/fr_selenium.py, tests/test_figure_resampler.py, tests/test_figure_resampler_selenium.py, tests/test_figurewidget_resampler.py, tests/utils.py
Fixes #119 
This PR does the following;
TODO: properly look at reset axes and/or autoscale behavior - this does not reset axes as we would expect (bc original range not in front-end..?)
(P.S. once merged into main we should update PR #115 with the latest main)
=> :bug: update layout `axes range` bug

plotly_resampler/figure_resampler/figure_resampler_interface.py, plotly_resampler/registering.py, tests/test_figure_resampler.py, tests/test_figurewidget_resampler.py
Checking for NaNs is a major bottleneck in graph construction time. This flag gives the user control to disable this check, which should be used when the user is sure that
(a) the data contains no NaNs, or
(b) the downsampler can handle NaNs (e.g., EveryNthPoint)
=> :sparkles: add check_nans to add_trace(s)

plotly_resampler/__init__.py, plotly_resampler/aggregation/aggregators.py, plotly_resampler/aggregation/algorithms/lttb_c.py, plotly_resampler/aggregation/algorithms/lttbc.c, plotly_resampler/figure_resampler/figure_resampler.py, plotly_resampler/figure_resampler/figure_resampler_interface.py, plotly_resampler/figure_resampler/figurewidget_resampler.py, plotly_resampler/figure_resampler/utils.py
Used the python library [refurb](https://github.com/dosisod/refurb) against this repo and added most of the suggested changes.
Feel free to counteract any!
I think good future work will be dropping support for anything lower than python 3.9 as well and porting all annotations to future syntax in terms of codebase wide changes.
=> :broom: refurb cleanup + one typo

CONTRIBUTING.md
Mostly removed the lines describing how contributing on GitHub works and plugging this info via [this url](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)
=> :broom: clean up CONTRIBUTING.md

plotly_resampler/figure_resampler/utils.py, tests/test_utils.py
Fixes #171 
When rounding numbers or timedelta's, None is returned when the number (i.e., diff) == 0
=> :bug: return None when rounding 0

tests/test_figure_resampler.py
Adds a test for #123, this test whether the `FigureResampler.show_dash` keeps hanging if a `FigureResampler` Dash app is already running on the same port.
=> test: add tests for #123

CONTRIBUTING.md, docs/sphinx/FAQ.rst, docs/sphinx/conf.py, poetry.lock, pyproject.toml
=> Remove locked werkzeug dependency due to CVE-2023-25577

.github/workflows/lint.yml, .github/workflows/test.yml, CONTRIBUTING.md, plotly_resampler/figure_resampler/figure_resampler.py, poetry.lock, pyproject.toml
=> :sparkles: making `flask_cors` & `kaleido` optional

docs/sphinx/FAQ.rst
Addresses comments concerning slower graph construction for datetime arrays in #180
=> docs: describe solution in FAQ for slow datetime arrays

plotly_resampler/aggregation/aggregation_interface.py, plotly_resampler/aggregation/aggregators.py, plotly_resampler/aggregation/algorithms/lttb_c.py, plotly_resampler/aggregation/plotly_aggregator_parser.py, plotly_resampler/figure_resampler/figure_resampler.py, plotly_resampler/figure_resampler/figure_resampler_interface.py, tests/test_aggregators.py, tests/utils.py
This uses an identical interface as utilized in tsdownsample.
While reworking the interface I realized that the np array interface PR will result in a hard lock-in to the in-memory numpy arrays. To overcome this, we should be much more flexible in (1) what dataformats we support (np.array, pandas.Series, polars. …), and (2) how our data aggregation interoperates on that data (currently tsdownsample only works on numpy arrays -> requires converting other datat types to this :/ )
=> Rework aggregator interface 

plotly_resampler/figure_resampler/figure_resampler_interface.py, tests/test_figure_resampler.py, tests/test_figurewidget_resampler.py, tests/utils.py
=> Fixes #210

README.md, plotly_resampler/aggregation/plotly_aggregator_parser.py, tests/test_figure_resampler.py
=> Datetime range

plotly_resampler/figure_resampler/figure_resampler_interface.py, tests/test_figure_resampler.py, tests/test_figurewidget_resampler.py
=> :bug: convert trace props to array + check for nan removal

plotly_resampler/figure_resampler/figure_resampler_interface.py
=> :eyes: comment out reset layout

.github/workflows/codeql.yml, .github/workflows/test.yml, README.md
Adds github code scanning to the repository.
=> 👷 build: create codeql.yml

plotly_resampler/figure_resampler/utils.py
Noticed this FutureWarning when running plotly-resampler with pandas 2.2.0
```
<...>\Lib\site-packages\plotly_resampler\figure_resampler\utils.py:177: FutureWarning:
'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
```
From what I can see lower case 'h' was required since pandas 1.0, so this change should not break compatibility with older pandas versions.
Let me know if you would prefer for me to open an issue before looking at this PR.
=> Address FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.

plotly_resampler/aggregation/aggregators.py
Commit e73cc8d98b8c00f0a1795fff0dc55a9e37ab4fae moved the location of `minmax_operator.png`. This PR adjusts sources to changes. Relevant page can be found [here](https://predict-idlab.github.io/plotly-resampler/v0.10.0/api/aggregation/aggregators/#aggregation.aggregators.MinMaxOverlapAggregator).
=> Update minmax operator image

.github/workflows/test.yml, plotly_resampler/figure_resampler/figure_resampler_interface.py, plotly_resampler/figure_resampler/figurewidget_resampler.py, tests/fr_selenium.py, tests/test_figure_resampler_selenium.py, tests/test_figurewidget_resampler.py
When using `FigureWidgetResampler` using traces that are not resampled (e.g., Histogram, Bar, etc.), the following action chain resulted in a `TypeError` (because `update_data` is NoUpdate)
1. Zoom in in a region
2. Reset the axis (house icon)
Reproducible code:
```py
import numpy as np
from plotly_resampler import FigureWidgetResampler
x = np.random.randn(100)
fig = FigureWidgetResampler(go.Figure(go.Histogram(x=x)))
fig
```
Error :arrow_down:
=> fix: check if update_data contains update before batch_update

tests/test_utils.py
This PR parametrizes tests on `is_figure` in `test_utils.py`.
xref #168
=> Parametrize test_utils.py on is_figure

plotly_resampler/figure_resampler/figure_resampler_interface.py, tests/test_figure_resampler.py
Related PR #336 
Related issue: https://github.com/predict-idlab/plotly-resampler/issues/335 (which contains a thorough explanation)
Example to try:
```python
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from plotly_resampler import FigureResampler
time = 1000
N = 4001  # number of points in the subplot exceeds default_n_shown_samples
x = np.linspace(0.0, time, N, endpoint=False)
y = np.cos(1 / 2 * np.pi + 2 / 50 * np.pi * x)
fig = FigureResampler(make_subplots(rows=2, cols=1), verbose=True)
fig.add_trace(go.Scattergl(), hf_x=x, hf_y=y, row=1, col=1)
fig.add_trace(go.Scattergl(), hf_x=x, hf_y=-y, row=2, col=1)
fig.update_xaxes(
range=[0, np.ceil(x[-1])],  # set the x range of the subplot
row=1,
col=1,
)
fig.update_xaxes(
range=[0, …
```
=> Fix: Add xaxis.range[0]/[1] If Not Exist

plotly_resampler/figure_resampler/figure_resampler.py, plotly_resampler/figure_resampler/jupyter_dash_persistent_inline_output.py, poetry.lock, pyproject.toml, tests/test_figure_resampler.py
=> Fix: Import JupyterDashPersistentInlineOutput only when needed
